(define (problem atwork1)
        (:domain atwork)
        (:objects o1 o2 o3 - object
		 s1 s2 s3 - place
		 b-it-bots - robot
		)
        (:init (On o1 s1 center)
	       (On o2 s2 center)
	       (On o3 s3 center)
	       (Free s1 left)
	       (Free s1 leftcenter)
	       (not(Free s1 center))
	       (Free s1 rightcenter)
	       (Free s1 right)
	       (Free s2 left)
	       (Free s2 leftcenter)
	       (not(Free s2 center))
	       (Free s2 rightcenter)
	       (Free s2 right)
	       (Free s3 left)
	       (Free s3 leftcenter)
	       (not(Free s3 center))
	       (Free s3 rightcenter)
	       (Free s3 right)
	       (Empty b-it-bots)
	       (not(Full b-it-bots))
               (Check b-it-bots)
	       (PlatformFree b-it-bots p1)
	       (PlatformFree b-it-bots p2)
	       (PlatformFree b-it-bots p3)
	       (not(Safe b-it-bots))
	       (At s1)
	       (not(At s2))
	       (not(At s3))
	       (= (distance s1 s1)  0)
	       (= (distance s2 s2)  0)
	       (= (distance s3 s3)  0)
	       (= (distance s1 s2)  1)
               (= (distance s1 s3) 2)
               (= (distance s2 s1) 1)
               (= (distance s2 s3) 1)
               (= (distance s3 s1) 2)
               (= (distance s3 s2) 1)
	       (= (total-cost) 0))
   (:goal 
     (and (On o1 s3 left)
	  (On o2 s3 center)
	  (On o3 s3 right)
     )
   )
   (:metric minimize (total-cost))
)

