(define (problem atwork3)
        (:domain atwork)	
        (:objects o1 o2 o3 o4 o5 o6 o7 o8 - object
		   s1 s2 s3 s4 s5 s6 START END - place 
		   youbot - robot)
        (:metric minimize (total-cost))
        (:init (On o1 s5 right)
	       (On o4 s5 center)
	       (On o5 s5 left)
	       (On o5 s2 right)
	       (On o3 s2 center)
	       (On o7 s2 left)
	       (On o2 s3 left)
	       (On o6 s3 center)
	       (On o8 s3 right) 
	       (Free s1 left)
	       (Free s1 leftcenter)
	       (Free s1 center)
	       (Free s1 rightcenter)
	       (Free s1 right)
	       (not (Free s2 left))
	       (Free s2 leftcenter)
	       (not(Free s2 center))
	       (Free s2 rightcenter)
	       (not(Free s2 right))
	       (not(Free s3 left))
	       (Free s3 leftcenter)
	       (not(Free s3 center))
	       (Free s3 rightcenter)
	       (not(Free s3 right))
	       (Free s4 left)
	       (Free s4 leftcenter)
	       (Free s4 center)
	       (Free s4 rightcenter)
	       (Free s4 right)
	       (not(Free s5 left))
	       (Free s5 leftcenter)
	       (not(Free s5 center))
	       (Free s5 rightcenter)
	       (not(Free s5 right))
	       (Free s6 left)
	       (Free s6 leftcenter)
	       (Free s6 center)
	       (Free s6 rightcenter)
	       (Free s6 right)
	       (Empty youbot)
	       (not(Check youbot))
	       (not(Full youbot))
	       (PlatformFree youbot p1)
	       (PlatformFree youbot p2)
	       (PlatformFree youbot p3)
	       (not(Safe youbot))
	       (At START)
	       (not(At s1))
	       (not(At s2))
	       (not(At s3))
	       (not(At s4))
	       (not(At s5))
	       (not(At s6))
	       (not(At END))
	       (= (distance s1 s2) 5)
               (= (distance s1 s3) 10)
	       (= (distance s1 s4) 25)
               (= (distance s1 s5) 20)
	       (= (distance s1 s6) 25)
               (= (distance s2 s3) 5)
               (= (distance s2 s4) 30)
               (= (distance s2 s5) 20)
               (= (distance s2 s6) 25)
               (= (distance s3 s4) 20)
	       (= (distance s3 s5) 20)
               (= (distance s3 s6) 15)
	       (= (distance s4 s5) 10)
               (= (distance s4 s6) 5)
	       (= (distance s5 s6) 10)
	       (= (total-cost) 0))
   (:goal 
     (and (On o3 s1 right)
	  (On o4 s1 center)
	  (On o6 s1 left)
	  (On o5 s4 right)
	  (On o5 s4 center)
	  (On o8 s4 left)
	  (On o1 s6 left)
	  (On o2 s6 center)
	  (On o7 s6 right)
	  (At END)
     )
   )
)

