(define (problem atwork2)
        (:domain atwork)	
	(:objects o1 o2 o3 o4 - object
		s1 s2 s3 START END - place
		youbot - robot)
        (:init (On o1 s3 left)
	       (On o2 s3 leftcenter)
	       (On o2 s3 center)		
	       (On o3 s3 rightcenter)
	       (On o4 s3 right)
	       (Free s1 left)
	       (Free s1 leftcenter)
	       (Free s1 center)
	       (Free s1 rightcenter)
	       (Free s1 right)
	       (not(Free s3 left))
	       (not(Free s3 leftcenter))
	       (not(Free s3 center))
	       (not(Free s3 rightcenter))
	       (not(Free s3 right))
	       (Empty youbot)
	       (not(Check youbot))
	       (not(Full youbot))
	       (PlatformFree youbot p1)
	       (PlatformFree youbot p2)
	       (PlatformFree youbot p3)
	       (not(Safe youbot))
	       (At START)
	       (not(At s1))
	       (not(At s2))
	       (not(At s3))
	       (not(At END)))
   (:goal 
     (and (On o1 s1 left)
	  (On o2 s1 leftcenter)
	  (On o2 s1 center)
	  (On o3 s1 rightcenter)
	  (On o4 s1 right)
	  (At END)
     )
   )
)


