(define (problem atwork2)
        (:domain atwork)	
	(:objects o1 o2 o3 o4 -object
		s1 s2 s3 s4 s5 START END -place
		youbot -robot)
        (:init (On o1 s3)
	       (On o2 s3)
	       (On o2 s3)		
	       (On o3 s3)
	       (On o4 s3)
	       (At START)
	       (not(Safe youbot))
	       (not(At s2))
	       (not(At s3))
	       (not(At s4))
	       (not(At s5)))
   (:goal 
     (and (On o1 s1)
	  (On o2 s1)
	  (On o2 s1)
	  (On o3 s1)
	  (On o4 s1)
	  (At END)
     )
   )
)

